# Generated by Django 2.2.12 on 2021-04-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.Category')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=5, null=True)),
                ('commissioning_date', models.DateField(null=True)),
                ('comment', models.CharField(max_length=50, null=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.ItemType')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
            ],
        ),
    ]
