# Generated by Django 2.2.12 on 2021-05-06 10:32

from django.db import migrations


def blank_charfields(apps, schema_editor):
    items = apps.get_model('items', 'Item')

    for item in items.objects.filter(comment=None):
        item.comment = ''
        item.save()

    for item in items.objects.filter(serial=None):
        item.serial = ''
        item.save()

    for item in items.objects.filter(size=None):
        item.size = ''
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_decommissioning_date'),
    ]

    operations = [
        migrations.RunPython(blank_charfields),
    ]
