# Generated by Django 2.2.12 on 2021-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210506_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
