# Generated by Django 2.2.12 on 2021-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210506_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
