# Generated by Django 2.2.12 on 2021-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
